---
name: 'member-bookmarks'
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - NZTA\MemberBookmark\Extensions\BookmarksSiteConfigExtension

SilverStripe\Security\Member:
  extensions:
    - NZTA\MemberBookmark\Extensions\BookmarksMemberExtension

SilverStripe\Security\Group:
  extensions:
    - NZTA\MemberBookmark\Extensions\BookmarksGroupExtension

PageController:
  extensions:
    - NZTA\MemberBookmark\Extensions\BookmarksPageControllerExtension
